apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ziad-test-bucket
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-1
    forceDestroy: true
  providerConfigRef:
    name: default